# Generated by Django 4.2.7 on 2024-03-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teretana', '0002_alter_profile_spol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pretplata',
        ),
    ]
